<?php

declare(strict_types=1);

// ABOUTME: Imports docker-compose.yaml files into seaman configuration.
// ABOUTME: Detects recognized services and preserves custom services.

namespace Seaman\Service;

use Seaman\Exception\FileNotFoundException;
use Seaman\Exception\InvalidConfigurationException;
use Seaman\Service\Detector\ServiceDetector;
use Seaman\ValueObject\CustomServiceCollection;
use Seaman\ValueObject\ImportResult;
use Seaman\ValueObject\RecognizedService;

final readonly class ComposeImporter
{
    private FileReader $fileReader;

    public function __construct(
        private ServiceDetector $detector,
        ?FileReader $fileReader = null,
    ) {
        $this->fileReader = $fileReader ?? new FileReader();
    }

    /**
     * Import a docker-compose file and categorize services.
     *
     * @throws FileNotFoundException When file not found
     * @throws InvalidConfigurationException When structure is invalid
     */
    public function import(string $composePath): ImportResult
    {
        if (!$this->fileReader->exists($composePath)) {
            throw FileNotFoundException::create($composePath, 'docker-compose file not found');
        }

        $composeData = $this->fileReader->readYaml($composePath);

        if (empty($composeData)) {
            throw new InvalidConfigurationException('Invalid docker-compose structure');
        }

        if (!isset($composeData['services']) || !is_array($composeData['services'])) {
            throw new InvalidConfigurationException('No services found in docker-compose file');
        }

        /** @var array<string, array<string, mixed>> $services */
        $services = $composeData['services'];

        return $this->categorizeServices($services);
    }

    /**
     * @param array<string, array<string, mixed>> $services
     */
    private function categorizeServices(array $services): ImportResult
    {
        /** @var array<string, RecognizedService> $recognized */
        $recognized = [];

        /** @var array<string, array<string, mixed>> $custom */
        $custom = [];

        foreach ($services as $name => $config) {
            // Skip Seaman-generated app service
            if ($this->isSeamanGeneratedService($name, $config)) {
                continue;
            }

            $detected = $this->detector->detectService($name, $config);

            if ($detected !== null) {
                $recognized[$name] = new RecognizedService(
                    detected: $detected,
                    config: $config,
                );
            } else {
                $custom[$name] = $config;
            }
        }

        return new ImportResult(
            recognized: $recognized,
            custom: new CustomServiceCollection($custom),
        );
    }

    /**
     * Check if a service was generated by Seaman and should be skipped.
     *
     * @param array<string, mixed> $config
     */
    private function isSeamanGeneratedService(string $name, array $config): bool
    {
        // Skip app service with Seaman image
        if (isset($config['image']) && is_string($config['image'])) {
            if (str_starts_with($config['image'], 'seaman/seaman')) {
                return true;
            }
        }

        // Skip app service that builds from .seaman/Dockerfile
        if (isset($config['build']) && is_array($config['build'])) {
            $dockerfile = $config['build']['dockerfile'] ?? null;
            if (is_string($dockerfile) && str_contains($dockerfile, '.seaman/Dockerfile')) {
                return true;
            }
        }

        return false;
    }
}
