<?php

declare(strict_types=1);

// ABOUTME: Builds PHAR executable using Box.
// ABOUTME: Creates distributable seaman.phar in build directory.

namespace Seaman\Command;

use Seaman\Contracts\Decorable;
use Seaman\EventListener\ListenerDiscovery;
use Seaman\UI\Terminal;
use Seaman\UI\Widget\Spinner\SpinnerFactory;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Process\Process;

#[AsCommand(
    name: 'seaman:build',
    description: 'Build PHAR executable using Box',
    aliases: ['build'],
)]
class BuildCommand extends AbstractSeamanCommand implements Decorable
{
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $projectRoot = (string) getcwd();

        $buildDir = $this->ensureBuildDirectory($projectRoot);
        $boxPath =  $this->ensureBoxIsInstalled($projectRoot);

        $this->generateListenersConfig($projectRoot);

        // Run box compile
        $process = new Process(
            [$boxPath, 'compile', '--working-dir=' . $projectRoot],
            $projectRoot,
            null,
            null,
            300, // 5 minutes timeout
        );

        SpinnerFactory::for($process, sprintf('Compiling seaman.phar using Box at: %s', $boxPath));

        if (!$process->isSuccessful()) {
            Terminal::error('Failed to build PHAR');
            // Terminal::output()->writeln($process->getErrorOutput());
            return Command::FAILURE;
        }

        $pharPath = $buildDir . '/seaman.phar';
        if (!file_exists($pharPath)) {
            Terminal::error('PHAR file was not created at expected location: ' . $pharPath);
            return Command::FAILURE;
        }

        Terminal::success('PHAR built successfully: ' . $pharPath);
        Terminal::output()->writeln('You can now distribute build/seaman.phar');

        return Command::SUCCESS;
    }

    private function generateListenersConfig(string $projectRoot): void
    {
        $discovery = new ListenerDiscovery($projectRoot . '/src/Listener');
        $listeners = $discovery->discover();

        $configDir = $projectRoot . '/config';
        if (!is_dir($configDir)) {
            mkdir($configDir, 0755, true);
        }

        $content = "<?php\n";
        $content .= "// Auto-generated by BuildCommand - do not edit manually\n\n";
        $content .= "declare(strict_types=1);\n\n";
        $content .= "use Seaman\\EventListener\\EventListenerMetadata;\n\n";
        $content .= "return [\n";

        foreach ($listeners as $metadata) {
            $content .= sprintf(
                "    new EventListenerMetadata(\n"
                . "        className: \\%s::class,\n"
                . "        event: '%s',\n"
                . "        priority: %d,\n"
                . "    ),\n",
                $metadata->className,
                $metadata->event,
                $metadata->priority,
            );
        }

        $content .= "];\n";

        file_put_contents($configDir . '/listeners.php', $content);
        Terminal::success('Listeners configuration generated');
    }

    private function ensureBuildDirectory(string $projectRoot): string
    {
        // Ensure build directory exists
        $buildDir = $projectRoot . '/build';
        if (!is_dir($buildDir)) {
            if (!mkdir($buildDir, 0755, true)) {
                Terminal::error('Failed to create build directory');
                exit(Command::FAILURE);
            }
        }

        return $buildDir;
    }

    private function ensureBoxIsInstalled(string $projectRoot): string
    {
        // Check if box is available
        $boxPath = $projectRoot . '/vendor/bin/box';
        if (!file_exists($boxPath)) {
            Terminal::error('Box not found. Please run: composer install --dev');
            exit(Command::FAILURE);
        }

        return $boxPath;
    }

}
