<?php

declare(strict_types=1);

// ABOUTME: Builds PHAR executable using Box.
// ABOUTME: Creates distributable seaman.phar in build directory.

namespace Seaman\Command;

use Seaman\Contract\Decorable;
use Seaman\EventListener\ListenerDiscovery;
use Seaman\Exception\BinaryNotFoundException;
use Seaman\UI\Terminal;
use Seaman\UI\Widget\Spinner\SpinnerFactory;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Process\Process;

#[AsCommand(
    name: 'seaman:build',
    description: 'Build PHAR executable using Box',
    aliases: ['build'],
)]
class BuildCommand extends ModeAwareCommand implements Decorable
{
    /**
     * @throws BinaryNotFoundException
     */
    protected function supportsMode(\Seaman\Enum\OperatingMode $mode): bool
    {
        return true; // Works in all modes
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $projectRoot = base_path();

        $buildDir = $this->ensureDistDirectory($projectRoot);
        $boxPath =  $this->ensureBoxIsInstalled($projectRoot);

        $this->generateListenersConfig($projectRoot);

        // Install production dependencies only
        //$this->installProductionDependencies($projectRoot);

        // Run box compile
        $process = new Process(
            [$boxPath, 'compile', '--working-dir=' . $projectRoot],
            $projectRoot,
            null,
            null,
            300, // 5 minutes timeout
        );

        SpinnerFactory::for($process, sprintf('Compiling seaman.phar using Box at: %s', $boxPath));

        // Restore dev dependencies
        //$this->restoreDevDependencies($projectRoot);

        if (!$process->isSuccessful()) {
            Terminal::error('Failed to build PHAR');
            return Command::FAILURE;
        }

        $pharPath = $buildDir . '/seaman.phar';
        if (!file_exists($pharPath)) {
            Terminal::error('PHAR file was not created at expected location: ' . $pharPath);
            return Command::FAILURE;
        }

        Terminal::success('PHAR built successfully: ' . $pharPath);
        Terminal::output()->writeln(['', '  💙 Crafted a new seaman release. You can now distribute dist/seaman.phar']);

        return Command::SUCCESS;
    }

    private function generateListenersConfig(string $projectRoot): void
    {
        $discovery = new ListenerDiscovery($projectRoot . '/src/Listener');
        $listeners = $discovery->discover();

        $configDir = $projectRoot . '/config';
        if (!is_dir($configDir)) {
            mkdir($configDir, 0755, true);
        }

        $content = "<?php\n";
        $content .= "// Auto-generated by BuildCommand - do not edit manually\n\n";
        $content .= "declare(strict_types=1);\n\n";
        $content .= "use Seaman\\EventListener\\EventListenerMetadata;\n\n";
        $content .= "return [\n";

        foreach ($listeners as $metadata) {
            $content .= sprintf(
                "    new EventListenerMetadata(\n"
                . "        className: \\%s::class,\n"
                . "        event: '%s',\n"
                . "        priority: %d,\n"
                . "    ),\n",
                $metadata->className,
                $metadata->event,
                $metadata->priority,
            );
        }

        $content .= "];\n";

        file_put_contents($configDir . '/listeners.php', $content);
        Terminal::success('Listeners configuration generated');
    }

    private function ensureDistDirectory(string $projectRoot): string
    {
        // Ensure build directory exists
        $buildDir = $projectRoot . '/dist';
        if (!is_dir($buildDir)) {
            if (!mkdir($buildDir, 0755, true)) {
                Terminal::error('Failed to create dist directory');
                exit(Command::FAILURE);
            }
        }

        return $buildDir;
    }

    private function ensureBoxIsInstalled(string $projectRoot): string
    {
        // Check if box is available
        $boxPaths = [$projectRoot . '/vendor/bin/box', $projectRoot . '/bin/box', '/usr/local/bin/box'];
        foreach ($boxPaths as $path) {
            if (file_exists($path)) {
                return $path;
            }
        }

        Terminal::error('Box not found. Please run: composer install --dev');
        exit(Command::FAILURE);
    }

    private function installProductionDependencies(string $projectRoot): void
    {
        $process = new Process(
            ['composer', 'install', '--no-dev', '--no-interaction', '--optimize-autoloader', '--classmap-authoritative'],
            $projectRoot,
            null,
            null,
            300,
        );

        SpinnerFactory::for($process, 'Installing production dependencies only');

        if (!$process->isSuccessful()) {
            Terminal::error('Failed to install production dependencies');
            Terminal::output()->writeln($process->getErrorOutput());
            exit(Command::FAILURE);
        }
    }

    private function restoreDevDependencies(string $projectRoot): void
    {
        $process = new Process(
            ['composer', 'install', '--no-interaction'],
            $projectRoot,
            null,
            null,
            300,
        );

        $process->run();

        if (!$process->isSuccessful()) {
            Terminal::error('Failed to restore dev dependencies. You may need to run composer install manually.');
        }
    }

}
