<?php
// Auto-generated by BuildCommand - do not edit manually

declare(strict_types=1);

use Seaman\EventListener\EventListenerMetadata;

return [
    new EventListenerMetadata(
        className: \Seaman\Listener\LogCommandListener::class,
        event: 'console.command',
        priority: 100,
    ),
    new EventListenerMetadata(
        className: \Seaman\Listener\NotifyOnErrorListener::class,
        event: 'console.error',
        priority: 0,
    ),
];
